### PR TITLE
Documentation Update

### PR DESCRIPTION
**Pull request by marohrdanz**
This pull request (PR) is for large changes to the documentation website. These changes are based on user and team feedback.

The two links below allow for comparison of 1. the changes in this PR and 2. the current version of the documentation:

1. Changes proposed in this PR: https://marohrdanz.github.io/NGCHM-R/index.html
2. Current version of the documentation: https://md-anderson-bioinformatics.github.io/NGCHM-R/

Key changes:

- Revamped most of the vignettes, in particular the main "Getting Started" vignette.
- Changed the color scheme to use the MD Anderson palette
- Moved YouTube links to main menu
- Updated the \_pgkdown.yml file for bootstrap 5
- Added search box and dark mode option
- Made site focused on the R package rather than NG-CHMs in general

### CODE REVIEW

**Review by jmelott — CHANGES_REQUESTED** [review]
Hi Mary,  For all but the functions page (and some of those) I tried all the links and read the text and found the following issues:

The Source links at the top of the following vignettes generate 404's when you try to go to the pages.  "Getting Started", all links under Vignettes menu except last one.

Several vignettes, but not all, show in console: "Page layout may be unexpected due to Quirks Mode."

On "Getting Started" vignette, the link for "Export to HTML, .ngchm, or PDF" doesn't work.
That link is different from the equivalent one on the right sidebar which does work though the one that works has 2 dashes instead of 1 between the words html and ngchm so the non-working one was probably the desired one.

The installation page says that the package requires R >= 3.5, but the package on CRAN says that it requires R >= 3.4.  I can't remember, do we still require git, tar, scp, & ssh.  I was thinking some of those requirements have been removed.  The CRAN entry only lists Java >=11 and Git.

In the generic code example on getting started, they shouldn't need to load the NGCHMDemoData library since they're not using data from it, should they?

You also have the Demo Data example code in the page twice, the second being just before the "Create an NG-CHM" section, but the code is slightly different from the version above.  I'd question whether the second one is needed any more, especially since it might not work since it doesn't have the library commands for support files or NGCHM in it.

Neither of the examples actually require the htmltools package.  You include the instructions to load it in the "Embed into RMarkdown" section, so I'd question its inclusion in the examples.

For Matrix Color Data Map, it looks like none of the documentation specifies that the breakpoints for continuous color maps must be unique numbers in numerical order from lowest to highest.  That might help some beginners to avoid some errors of putting them in the wrong order.

**Comment by ChrisWakefield** [comment]
I'll just hold off since James listed several things to be fixed.

**Comment by marohrdanz** [comment]
Thank you for your feedback @jmelott. Here's a rundown of your comments and corresponding changes:

- source link 404's: The 404's were because of name changes of some of the vignette file names combined with my fork demo (under marohrdanz) using 'MD-Anderson-Bioinformatics' for this links. I made a commit **only in the demo fork** so that the URLs work. This commit is NOT part of the MD-Anderson-Bioinformatics/NGCHM-R repo: https://github.com/marohrdanz/NGCHM-R/commit/2c845f0cc29549b3c06623b04b7ec81f3ac04bb0. Once this PR is merged, the source links will not return 404's because the source files will exist in the main branch of this repo.
- Quirks mode: these console messages are from the embedded NG-CHMs, not from the R package vignettes. (the same browser console that shows the warning also shows where it arises, and I verified they are the embedded NG-CHM file names. If you create an HTML file via `chmExportToHTML` you will also see these warnings when opening it in a browser).
- Broken "Export to HTML, .ngchm, or PDF" link: fixed in 5848bc0 
- R versions: I set the version to R >= 3.5. Rationale in commit message 9abf0a3
- git, tar, scp, and ssh requirements: I listed tar, scp, and ssh as optional on the installation page. Rationale in commit message fd717f0
- Loading NGCHMDemoData and htmltools: addressed in 805ff8c
- "Demo Data example code in the page twice": The full code block is not twice--that second is only the part for reading demo data and formatting it for NGCHM. Regarding your statement "I'd question whether the second one is needed any more": I include it for reasons similar to why `hm <- chmNew("TCGA BRCA Expression", matrix_data)` is included in the "Create an NG-CHM" section--to help the reader better understand the code examples. I did follow your suggestion of making the format of the code the same in 4b50feb
- Note about breakpoints: addressed in cdf327c

**Review by bmbroom — COMMENTED** [review]
Looking just at the Getting Started section.

Overall, this looks very good.  I just have some comments in the "Add a Covariate Bar" section.

first sentence: create -> creates
first sentence: bar -> object
Reason for the later:
Package has covariate objects and covariate bar objects.  The first contains details of the covariate. CovariateBar adds visualization parameters: e.g. height of bar, visibility, etc.  chmNewCovariate just creates a covariate. chmAddCovariateBar accepts either a covariate or a covariateBar.   A covariate is converted to a covariateBar using default values.  We don't need to go into all that detail here, but I would prefer to be technically correct.

third sentence: "covariate bar" -> "covariate".
fourth sentence: "covariate bar object" -> "covariate object".
fourth sentence: "type of covariate bar" -> "map axis to add the covariate bar to"

**Comment by bmbroom** [comment]
The Installation page appears much more daunting than the installation instructions on the Getting Started page.

Can you move the "System Requirements" section to after the "R Packages Installation" and explain in more detail the circumstances under which these would be needed.

Can you add the demo data package instructions to the "R Packages Installation" (as a optional component if you want the demo data).

**Comment by marohrdanz** [comment]
Thanks for the feedback @bmbroom. I addressed the concerns and updated the demo fork with the latest:

- Language in 'Add a Covariate Bar' section
  - 44a6bcf
  - https://marohrdanz.github.io/NGCHM-R/articles/getting-started.html#add-a-covariate-bar
- Installation page
  - 5ed9f16
  - https://marohrdanz.github.io/NGCHM-R/articles/Installation.html

**Comment by bmbroom** [comment]
The "Function Reference" tab shows a page titled "Package Index". Can/should they be the same?

I would prefer to split "Color Maps and Data Layers" into two sections. 
Add these functions to the "Colors and Color Maps" section: chmAddColorMap, chmColorMap()<-, chmColors(), chmColors()<-

Create a new section "Adding Scatter Plot Coordinates" with the following functions:
chmAddPCA()
chmAddReducedDim()
chmAddTSNE()
chmAddUMAP()
chmAddUWOT()

Create a new section "Changing row and column ordering and dendrograms" with the following functions:
chmColOrder()<-, chmRowOrder()<-
There are other ways to modify ordering that aren't functions.

Create a new section "Setting map properties"
chmHasProperty(), chmGetProperty(), chmNewProperty(), chmAddProperty(), chmProperty(), chmProperty()<-

Create a new section "Adding gaps to an NG-CHM" with the following function
chmTreeGaps()

I think chmAdd() should be documented.  I'm not sure where given the sections. Perhaps duplicate it in each relevant section?

The list under "All functions" contains a lot of functions that are either obsolete, for internal use only, or only applicable when connected to a shaidy server.  The first two require code clean up. We should probably document the latter, but not for this update.  Is there any way we could discourage users from looking at functions in this section?  Maybe a disclaimer and hiding the list under an "open" button.  The alphabetical listing of all functions may be useful (is it? search works). I think it's also useful for us. otherwise I'd suggest disappearing it.

**Comment by marohrdanz** [comment]
Thanks @bmbroom 

I changed the title of the Function Reference page (a48d25c), added the additional sections (with some minor language tweaks to your suggested section headings--let me know if you want your suggestions verbatim) (63a70a3).

What sections are appropriate for `chmAdd()`?

For the "All Functions": if we think everything a typical user needs is already in one of the existing sections, we could just remove that section. I did that in the WIP commit (6d1eebf). This is what is currently displayed on the fork demo. What do you think?

**Comment by bmbroom** [comment]
Section titles look fine to me.

chmAdd applies to: Layers, Colormaps, Properties.
(It also applies to Datasets, Dialogs, and Axes, but we haven't otherwise documented them yet.)

We can discuss merits of including the whole list in tomorrow's meeting.

**Comment by jmelott** [comment]
Still some errors in the console, but otherwise no other issues found:

https://md-anderson-bioinformatics.github.io/NGCHM-R/index.html
Uncaught SyntaxError: Invalid or unexpected token (at index.html:125:49)

https://md-anderson-bioinformatics.github.io/NGCHM-R/articles/continuous-color-maps-and-data-layers.html
continuous-color-maps-and-data-layers.html:184 Uncaught SyntaxError: Invalid or unexpected token (at continuous-color-maps-and-data-layers.html:184:50)

**Comment by bmbroom** [comment]
Content-wise it looks like a great improvement.

**Review by jmelott — APPROVED** [review]

**Comment by marohrdanz** [comment]
I have received email confirmation from @bmbroom to merge this PR.

**Pull request merged**
