### PR TITLE
Allow for specification of cuts in chmNew()

### PR DESCRIPTION
**Pull request by marohrdanz**
Allow for specification of cuts (now called 'gaps') by adding the following arguments to the chmNew() function:

- rowGapLocations
- rowGapWidth
- rowTreeGaps
- colGapLocations
- colGapWidth
- colTreeGaps

Also addresses linked issues #4, #5, and #6.

### CODE REVIEW

**Comment by bmbroom** [comment]
It only makes sense to specify at most one of rowTreeGaps and rowGapLocations (similarly for columns).  We could add logic to forbid setting both at the same time.

I would also like to add a function for getting/setting the gap information between chmNew and the various export functions.  Having two fields to manage and ensure exclusivity between seems like a headache to both the user and the R package.

An alternative would be to introduce a new type, e.g. chmTreeCut(4), and allow it to be assigned to rowGapLocations (and get rid of rowTreeGaps from user's view).

Thus the following would be allowed:
chmNew (..., rowGapLocations = NULL, ...)
chmNew (..., rowGapLocations = c(10,20,30), ...)
chmNew (..., rowGapLocations = chmTreeCut(4), ...)

Similarly, we could add getter/setter functions:
chmRowGapLocations(hm)
chmRowGapLocations(hm) <- NULL
chmRowGapLocations(hm) <- c(10,20,30)
chmRowGapLocations(hm) <- chmTreeCut(4)

Function for generating JSON spec would generate the appropriate output based on the type of the field.

**Comment by marohrdanz** [comment]
I made updates to allow usage of the chmNew() function as suggested by @bmbroom 's comment from June 8th above.

The key change is to create an 'initialize' method for ngchmVersion2 (in the file allClasses.R) to parse and verify arguments. Combined with the chmNew() function definition (in the file functions.R), this allows users to write something like

```R
hm <- chmNew('myhm', dl1, rowGapLocations=c(3,5), rowGapWidth=3, colGapLocations=chmTreeGaps(3), colGapWidth=7)
```

E.g. specifying rowGapLocations/colGapLocations as either a list or chmTreeGaps while still creating appropriate slots to be interpreted by the existing ShaidyMapGen java code (e.g. rowCutLocations/colCutLocations and rowTreeCuts/colTreeCuts).

This PR is ready for review.

**Comment by bmbroom** [comment]
A couple of initial comments:
- The additional dependences on NGCHMDemoData and NGCHMSupportFiles warrants a bump in the minor version number, so update the version number to 0.13.0.
- The size of the .tar.gz file for the release package has increased from 8.0 MB to 15 MB!  This is because a) we haven't removed the old demo data (TCGA.GBM.EXPR) from this package yet, and b) index.md has been added.  The latter is about 10 MB uncompressed and I think it's a copy of the documentation page (which contains a large embedded NGCHM).

Can we remove index.md from the package builds?  e.g. add to .Rbuildignore

I think we want to deprecate but not yet remove the existing demo data.  Removing it will break lots of existing tutorials etc. but will eventually be necessary.

There are big differences between the current demo data in this package (TCGA.GBM.EXPR) and the one in the demodata package that we'll need to understand.

Still have to look at the gaps related changes.

**Comment by jmelott** [comment]
The NGCHMR software has been available in some form for almost a decade.    Doesn't it warrant being at least a 1.0.0 version by now?

Can we use a smaller and/or less complicated map for the demo and still provide a good example or even have the map load from the web somewhere instead of including it in the package?

**Comment by marohrdanz** [comment]
These few points are for PR #19 . So I committed the suggestions into master instead of opening another PR.

> * The additional dependences on NGCHMDemoData and NGCHMSupportFiles warrants a bump in the minor version number, so update the version number to 0.13.0.

I changed the version number in master in db0f9ff

> * The size of the .tar.gz file for the release package has increased from 8.0 MB to 15 MB!  This is because a) we haven't removed the old demo data (TCGA.GBM.EXPR) from this package yet, and b) index.md has been added.  The latter is about 10 MB uncompressed and I think it's a copy of the documentation page (which contains a large embedded NGCHM).
> 
> Can we remove index.md from the package builds? e.g. add to .Rbuildignore
> 

Added in a508117

**Comment by marohrdanz** [comment]
> Can we use a smaller and/or less complicated map for the demo and still provide a good example or even have the map load from the web somewhere instead of including it in the package?

This part of the purpose of the [NGCHMDemoData](https://github.com/MD-Anderson-Bioinformatics/NGCHMDemoData) package. So when we're sure external tutorials using data/TCGA.GBM.EXPR.rda have been updated, we'll remove that 7.8 MB file from this repo.

**Comment by marohrdanz** [comment]
> Does index.md need to be part of the main branch?

I verified in my fork of this project that it does not--we can render index.md in the same GitHub Action that builds the pgkdown webiste. I made a pull request that makes this change: #22 .

**Comment by bmbroom** [comment]
> > Can we use a smaller and/or less complicated map for the demo and still provide a good example or even have the map load from the web somewhere instead of including it in the package?
> 
> This part of the purpose of the [NGCHMDemoData](https://github.com/MD-Anderson-Bioinformatics/NGCHMDemoData) package. So when we're sure external tutorials using data/TCGA.GBM.EXPR.rda have been updated, we'll remove that 7.8 MB file from this repo.

Can we move (copy, then eventually remove) TCGA.GBM.EXPR.rda into the NGCHMDemoData package?

The reason I ask is because the Youtube "Creating NGCHM in R" video references it.  I can't "remove" it without redoing the video.  I looked at the video and while it's showing its age, I don't yet feel an **urgent** need to redo it (it's a lot of work).  I could try adding text to the description/pinned comment saying the data has moved to a new package.

**Review by jmelott — CHANGES_REQUESTED** [review]
There seem to be a lot of layout issues where extra tabs or spaces have been added to the new file and are pushing things far to the right where they are no longer in line with the other code as they were in the old files.    I suspect it was a matter of there being tabs and spaces in the original code and replacement values being used had a much larger conversion value for tabs than the original. Could this be cleaned up a bit before the code is merged so the code's not as hard to decipher?

**Comment by marohrdanz** [comment]
> There seem to be a lot of layout issues where extra tabs or spaces have been added to the new file and are pushing things far to the right where they are no longer in line with the other code as they were in the old files. I suspect it was a matter of there being tabs and spaces in the original code and replacement values being used had a much larger conversion value for tabs than the original. Could this be cleaned up a bit before the code is merged so the code's not as hard to decipher?

I made a commit (7c0b63b) that fixed indentation mismatches to try and make the file easier for me to decipher. It was not simply 'convert all spaces to tabs'. I thought about undoing it...but there were of course a lot of other changes in that file that are relevant to this pull request (I had to decipher the code in order to figure out what to change). If there are strong opinions, I can try my best to put the original indentation mismatches back in place. Are these changes making it harder to read in your IDE?

**Comment by marohrdanz** [comment]
> There seem to be a lot of layout issues where extra tabs or spaces have been added to the new file and are pushing things far to the right where they are no longer in line with the other code as they were in the old files. I suspect it was a matter of there being tabs and spaces in the original code and replacement values being used had a much larger conversion value for tabs than the original. Could this be cleaned up a bit before the code is merged so the code's not as hard to decipher?

Addressed in 3f3baa5

**Comment by marohrdanz** [comment]
> chmTreeGaps needs roxygen documentation, including @exports and @param numberOfCuts.

@bmbroom: addressed in 5f0b86a

**Comment by marohrdanz** [comment]
> Can we move (copy, then eventually remove) TCGA.GBM.EXPR.rda into the NGCHMDemoData package?

I made pull requests in both projects to do this if/when we want to go this route: 

- https://github.com/MD-Anderson-Bioinformatics/NGCHMDemoData/pull/1
-  https://github.com/MD-Anderson-Bioinformatics/NGCHM-R/pull/23

**Review by bmbroom — APPROVED** [review]

**Review by jmelott — APPROVED** [review]

**Pull request merged**
