### PR TITLE
For cran

### PR DESCRIPTION
**Pull request by bmbroom**
Updates to NGCHM in support of future submission to CRAN.

### CODE REVIEW

**Comment by marohrdanz** [comment]
I had a look at CRAN's policies, https://cran.r-project.org/web/packages/policies.html, and there are at least a few things I think we need to address before actual submission:

- Listing a designated 'Maintainer' in DESCRIPTION
- I think CRAN will complain about tsvio in the 'Imports', because tsvio appears to only be in GitHub.
- I think we have to specify where to get NGCHMSupportFiles and NGCHMDemoData because they are not (yet) in CRAN.

**Comment by bmbroom** [comment]
* Giving the role "cre" to a person in the Authors@R field is equivalent to specifying a maintainer.
* Plan to submit tsvio before NGCHM packages.
* Plan to submit the two NGCHM support packages concurrently.  Will include cross-references between them all.

**Comment by bmbroom** [comment]
P.S. Many, many, many other issues to address before we can make first CRAN submission attempt.

**Comment by jmelott** [comment]
Mary: If you're running R CMD check, you have to do so against the .tar.gz created by the build rather than against the source directory.  The build process creates the maintainer and author tags correctly in the gz file from the authors@R tag.  If you run the check against the source directory it will report authors and maintainer to be missing when using the authors@R in the description file.

**Comment by bmbroom** [comment]
I originally changed the examples in 8b4c33e0c9a40b483c58b5a9c442696f03cd745d back to TCGA.GBM.EXPR because I didn't know how to load TCGA.BRCA.ExpressionData explicitly.  Now I do, so we could change some of them back.  Nice to have variety.

**Review by marohrdanz — APPROVED** [review]
These changes seem in the right direction. I also went through the exercise of using this version to build an NGCHM.

**Review by ChrisWakefield — APPROVED** [review]
I'm fine with it.  I reviewed all the code changes, and Mary reports she ran it to build a NGCHM.  Please let's merge this before making too many more changes!

**Pull request merged**
